"""create_streak_tables

Revision ID: 06c5d750afdb
Revises: c0952a66c3ac
Create Date: 2026-06-12 00:50:07.006788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c5d750afdb'
down_revision: Union[str, Sequence[str], None] = 'c0952a66c3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streak_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('previous_streak', sa.Integer(), nullable=False),
    sa.Column('new_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streak_events_event_type'), 'streak_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_streak_events_user_id'), 'streak_events', ['user_id'], unique=False)
    op.create_table('user_streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('freeze_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_last_activity_date'), 'user_streaks', ['last_activity_date'], unique=False)
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_index(op.f('ix_user_streaks_last_activity_date'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_streak_events_user_id'), table_name='streak_events')
    op.drop_index(op.f('ix_streak_events_event_type'), table_name='streak_events')
    op.drop_table('streak_events')
    # ### end Alembic commands ###
