"""update_models_sprint1

Revision ID: 1efc8bdf8d71
Revises: 028a8509085f
Create Date: 2026-06-12 00:21:02.908676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1efc8bdf8d71'
down_revision: Union[str, Sequence[str], None] = '028a8509085f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('state_code', sa.String(length=50), nullable=True))
    op.add_column('user_preferences', sa.Column('diet_type', sa.String(length=50), nullable=True))
    op.add_column('user_preferences', sa.Column('transport_preference', sa.String(length=50), nullable=True))
    op.add_column('user_preferences', sa.Column('housing_type', sa.String(length=50), nullable=True))
    op.add_column('user_preferences', sa.Column('notification_enabled', sa.Boolean(), nullable=False))
    op.add_column('user_preferences', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('user_preferences', 'notifications_enabled')
    op.drop_column('user_preferences', 'mission_difficulty')
    op.drop_column('user_preferences', 'preferred_categories')
    op.drop_column('user_preferences', 'privacy_mode')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'state_code')
    op.drop_column('users', 'diet_type')
    op.drop_column('users', 'housing_type')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'transport_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transport_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('housing_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('diet_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('state_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('user_preferences', sa.Column('privacy_mode', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('preferred_categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('mission_difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user_preferences', 'updated_at')
    op.drop_column('user_preferences', 'notification_enabled')
    op.drop_column('user_preferences', 'housing_type')
    op.drop_column('user_preferences', 'transport_preference')
    op.drop_column('user_preferences', 'diet_type')
    op.drop_column('user_preferences', 'state_code')
    # ### end Alembic commands ###
