"""create_memory_tables

Revision ID: 6e1f5d5dcc00
Revises: c928ffb71b63
Create Date: 2026-06-12 23:00:15.820039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.custom_types


# revision identifiers, used by Alembic.
revision: str = '6e1f5d5dcc00'
down_revision: Union[str, Sequence[str], None] = 'c928ffb71b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable the pgvector extension in PostgreSQL
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_retrieval_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_type', sa.String(length=100), nullable=False),
    sa.Column('memories_retrieved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_retrieval_logs_user_id'), 'memory_retrieval_logs', ['user_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', app.database.custom_types.Vector(1536), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_memory_retrieval_logs_user_id'), table_name='memory_retrieval_logs')
    op.drop_table('memory_retrieval_logs')
    # ### end Alembic commands ###
