"""create_mission_tables

Revision ID: c0952a66c3ac
Revises: d5683109df38
Create Date: 2026-06-12 00:43:14.776719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0952a66c3ac'
down_revision: Union[str, Sequence[str], None] = 'd5683109df38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('estimated_co2_saving', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_templates_category'), 'mission_templates', ['category'], unique=False)
    op.create_index(op.f('ix_mission_templates_difficulty'), 'mission_templates', ['difficulty'], unique=False)
    op.create_table('user_missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mission_template_id', sa.UUID(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_template_id'], ['mission_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_missions_assigned_date'), 'user_missions', ['assigned_date'], unique=False)
    op.create_index(op.f('ix_user_missions_mission_template_id'), 'user_missions', ['mission_template_id'], unique=False)
    op.create_index(op.f('ix_user_missions_status'), 'user_missions', ['status'], unique=False)
    op.create_index(op.f('ix_user_missions_user_id'), 'user_missions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_missions_user_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_status'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_mission_template_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_assigned_date'), table_name='user_missions')
    op.drop_table('user_missions')
    op.drop_index(op.f('ix_mission_templates_difficulty'), table_name='mission_templates')
    op.drop_index(op.f('ix_mission_templates_category'), table_name='mission_templates')
    op.drop_table('mission_templates')
    # ### end Alembic commands ###
