"""create_simulation_tables

Revision ID: c6146f36d944
Revises: eaa2e8c139c5
Create Date: 2026-06-12 23:46:52.408767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6146f36d944'
down_revision: Union[str, Sequence[str], None] = 'eaa2e8c139c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_scenarios_user_id'), 'simulation_scenarios', ['user_id'], unique=False)
    op.create_table('simulation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['simulation_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_history_scenario_id'), 'simulation_history', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_simulation_history_user_id'), 'simulation_history', ['user_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('predicted_footprint', sa.Float(), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['simulation_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_scenario_id'), 'simulation_results', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_results_scenario_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_simulation_history_user_id'), table_name='simulation_history')
    op.drop_index(op.f('ix_simulation_history_scenario_id'), table_name='simulation_history')
    op.drop_table('simulation_history')
    op.drop_index(op.f('ix_simulation_scenarios_user_id'), table_name='simulation_scenarios')
    op.drop_table('simulation_scenarios')
    # ### end Alembic commands ###
