"""create_emission_and_footprint_tables

Revision ID: d5683109df38
Revises: e93e711dfc9a
Create Date: 2026-06-12 00:32:55.494837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5683109df38'
down_revision: Union[str, Sequence[str], None] = 'e93e711dfc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('factor_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('factor_source', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_activity_type'), 'emission_factors', ['activity_type'], unique=False)
    op.create_index(op.f('ix_emission_factors_category'), 'emission_factors', ['category'], unique=False)
    op.create_table('daily_footprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('transport_emissions', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('food_emissions', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('electricity_emissions', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('shopping_emissions', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_emissions', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_footprints_date'), 'daily_footprints', ['date'], unique=False)
    op.create_index(op.f('ix_daily_footprints_user_id'), 'daily_footprints', ['user_id'], unique=False)
    op.create_table('daily_footprint_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_footprint_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=False),
    sa.Column('calculated_emission', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_footprint_id'], ['daily_footprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_footprint_sources_activity_id'), 'daily_footprint_sources', ['activity_id'], unique=False)
    op.create_index(op.f('ix_daily_footprint_sources_daily_footprint_id'), 'daily_footprint_sources', ['daily_footprint_id'], unique=False)
    op.create_index(op.f('ix_daily_footprint_sources_emission_factor_id'), 'daily_footprint_sources', ['emission_factor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_footprint_sources_emission_factor_id'), table_name='daily_footprint_sources')
    op.drop_index(op.f('ix_daily_footprint_sources_daily_footprint_id'), table_name='daily_footprint_sources')
    op.drop_index(op.f('ix_daily_footprint_sources_activity_id'), table_name='daily_footprint_sources')
    op.drop_table('daily_footprint_sources')
    op.drop_index(op.f('ix_daily_footprints_user_id'), table_name='daily_footprints')
    op.drop_index(op.f('ix_daily_footprints_date'), table_name='daily_footprints')
    op.drop_table('daily_footprints')
    op.drop_index(op.f('ix_emission_factors_category'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_activity_type'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
